language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
jobs:
  include:
  - stage: test
    script:
    - "./mvnw clean verify"
deploy:
  provider: elasticbeanstalk
  access_key_id: <access_key>
  secret_access_key:
    secure: <encrypted_secret_ket>
  region: ap-northeast-2
  app: <app>
  env: <env>
  bucket_name: <s3_bucket>
  zip_file: <output path: usually in `/targe/blah.war`>
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^release.v[0-9]+\\.[0-9]+\\.[0-9]+"
stages:
- test
- deploy
